#%RAML 1.0 DocumentationItem
title:
content: |
  ** The Employee Management API** provides endpoints for managing employee information, including 
  - retrieving all employees 
  - adding a new employee  
  - retrieving a specific employee
  - updating a specific employee 
  - deleting a specific employee. | 
  The API uses JSON as the data interchange format.